/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerVirtualRouteImport } from './routes/customer/virtual'
import { Route as CustomerLayoutRouteImport } from './routes/customer/_layout'

const CustomerRouteImport = createFileRoute('/customer')()

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerVirtualRoute = CustomerVirtualRouteImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLayoutRoute = CustomerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerLayoutRoute
  '/customer/virtual': typeof CustomerVirtualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerLayoutRoute
  '/customer/virtual': typeof CustomerVirtualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/_layout': typeof CustomerLayoutRoute
  '/customer/virtual': typeof CustomerVirtualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/customer' | '/customer/virtual'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/customer' | '/customer/virtual'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/customer'
    | '/customer/_layout'
    | '/customer/virtual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomerRoute: typeof CustomerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/virtual': {
      id: '/customer/virtual'
      path: '/virtual'
      fullPath: '/customer/virtual'
      preLoaderRoute: typeof CustomerVirtualRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/_layout': {
      id: '/customer/_layout'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerLayoutRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerLayoutRoute: typeof CustomerLayoutRoute
  CustomerVirtualRoute: typeof CustomerVirtualRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerLayoutRoute: CustomerLayoutRoute,
  CustomerVirtualRoute: CustomerVirtualRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomerRoute: CustomerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
